### ISSUE TITLE
AttributeError: module 'scipy.signal' has no attribute 'hann'

### ISSUE THREAD

**Issue by scubanarc** [devbret/detailed-audio-analysis#1]
Python 3.10.12

Trying to parse an mp3 file, get this error in the first 5 seconds:

    AttributeError: module 'scipy.signal' has no attribute 'hann'

Installing requirements.txt produced the following:

pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting librosa==0.9.1
  Downloading librosa-0.9.1-py3-none-any.whl (213 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.1/213.1 KB 2.9 MB/s eta 0:00:00
Collecting numpy==1.23.1
  Downloading numpy-1.23.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 10.3 MB/s eta 0:00:00
Collecting scikit-learn>=0.19.1
  Downloading scikit_learn-1.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 15.1 MB/s eta 0:00:00
Collecting scipy>=1.2.0
  Downloading scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 5.4 MB/s eta 0:00:00
Collecting numba>=0.45.1
  Downloading numba-0.59.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 23.9 MB/s eta 0:00:00
Collecting resampy>=0.2.2
  Downloading resampy-0.4.3-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 23.9 MB/s eta 0:00:00
Collecting audioread>=2.1.5
  Downloading audioread-3.0.1-py3-none-any.whl (23 kB)
Collecting pooch>=1.0
  Downloading pooch-1.8.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 KB 5.1 MB/s eta 0:00:00
Collecting soundfile>=0.10.2
  Downloading soundfile-0.12.1-py2.py3-none-manylinux_2_31_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 14.2 MB/s eta 0:00:00
Collecting joblib>=0.14
  Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 KB 20.5 MB/s eta 0:00:00
Collecting decorator>=4.0.10
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting packaging>=20.0
  Downloading packaging-24.0-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 KB 5.1 MB/s eta 0:00:00
Collecting llvmlite<0.43,>=0.42.0dev0
  Downloading llvmlite-0.42.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 MB 4.5 MB/s eta 0:00:00
Collecting platformdirs>=2.5.0
  Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
Requirement already satisfied: requests>=2.19.0 in /usr/lib/python3/dist-packages (from pooch>=1.0->librosa==0.9.1->-r requirements.txt (line 1)) (2.25.1)
Collecting threadpoolctl>=3.1.0
  Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Collecting cffi>=1.0
  Downloading cffi-1.16.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (443 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 443.9/443.9 KB 17.5 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.22-py3-none-any.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.6/117.6 KB 10.8 MB/s eta 0:00:00
Installing collected packages: threadpoolctl, pycparser, platformdirs, packaging, numpy, llvmlite, joblib, decorator, audioread, scipy, pooch, numba, cffi, soundfile, scikit-learn, resampy, librosa
  WARNING: The scripts f2py, f2py3 and f2py3.10 are installed in '/home/username/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed audioread-3.0.1 cffi-1.16.0 decorator-5.1.1 joblib-1.4.2 librosa-0.9.1 llvmlite-0.42.0 numba-0.59.1 numpy-1.23.1 packaging-24.0 platformdirs-4.2.2 pooch-1.8.1 pycparser-2.22 resampy-0.4.3 scikit-learn-1.5.0 scipy-1.13.1 soundfile-0.12.1 threadpoolctl-3.5.0

**Comment by devbret** [comment]
Hello and thank you for bringing this to my attention. I pushed another update to the software recently. Have you tried pulling, and running the MP3 file again?

**Comment by scubanarc** [comment]
I just did a pull and got new files, but the exact same error persists. I made sure to:

    pip install -r requirements.txt

But all requirements are listed as met.  Os release is:

    PRETTY_NAME="Ubuntu 22.04.2 LTS"
    VERSION="22.04.2 LTS (Jammy Jellyfish)"

**Comment by devbret** [comment]
After looking into the issue, the source of the bug appears to be that the scipy library renamed the "hann" attribute to "get_window". Which is why you are receiving the error message.

The first debugging step is to open a Linux Terminal and update the scipy library. You can do this by running the following command: `pip install --upgrade scipy`.

I just ran/tested this script on my own Linux OS, and it worked successfully. Please consider running that script, and if the problem still persists, we can tackle this bug at the code level.

**Comment by devbret** [comment]
I have pushed a new version of the software, which includes an updated requirements.txt file. 

First, pull the new version of the software. Then make sure to run `pip install -r requirements.txt` again, as this will install specific versions of two libraries that are required for the app function properly.

If this doesn't resolve the issue, definitely let me know, and I will work on it further.

**Comment by scubanarc** [comment]
Final result is success! I first tried updating scipy like you suggested, and that did not work:

    pip install --upgrade scipy
    Defaulting to user installation because normal site-packages is not writeable
    Requirement already satisfied: scipy in /home/jason/.local/lib/python3.10/site-packages (1.13.1)
    Requirement already satisfied: numpy<2.3,>=1.22.4 in /home/jason/.local/lib/python3.10/site-packages (from scipy) (1.23.1)

It seems like pip didn't want to update my scipy. I don't know.

Then I got your second message. I pulled a new copy of the repo, ran the requirements update, and ran the program again and it worked perfectly. The new requirements.txt seems to have fixed it.

Thanks for your assistance and for sharing your work. This is very cool.

**Comment by devbret** [comment]
This is wonderful to hear! I'm glad that the issue has been worked out, and that you are enjoying the tool. I'm going to close this issue, given that everything seems to be working.

If any other bugs emerge, please let me know, and I will resolve them as quickly as possible.
